import {
  Activity,
  Archive,
  ArchiveRestore,
  Ban,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  Crown,
  Flag,
  FolderPlus,
  FolderX,
  Key,
  KeyRound,
  ListChecks,
  LogIn,
  LogOut,
  MessageCircle,
  Pencil,
  RotateCcw,
  Send,
  Shield,
  ShieldCheck,
  Target,
  Trash2,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
} from "lucide-react";

// String → component map. Keep the keys aligned with what the server
// writes into activity.icon so the UI can render a meaningful glyph
// for every event.
const iconMap = {
  activity: Activity,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  ban: Ban,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "clipboard-list": ClipboardList,
  crown: Crown,
  flag: Flag,
  "folder-plus": FolderPlus,
  "folder-x": FolderX,
  key: Key,
  "key-round": KeyRound,
  "list-checks": ListChecks,
  "log-in": LogIn,
  "log-out": LogOut,
  "message-circle": MessageCircle,
  pencil: Pencil,
  "rotate-ccw": RotateCcw,
  send: Send,
  shield: Shield,
  "shield-check": ShieldCheck,
  target: Target,
  "trash-2": Trash2,
  user: User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  users: Users,
};

export function getActivityIcon(name) {
  return iconMap[name] ?? Activity;
}
